service: demo-app

useDotenv: true

custom:
  region: us-east-1
  userPoolName: demo-users

frameworkVersion: '2'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ${self:custom.region}
  logs:
    httpApi: true
  httpApi:
    authorizers:
      apiAuth:
        type: request
        functionName: authorizerFunc
        enableSimpleResponses: true
        identitySource:
          - $request.header.CustomAuth
  environment:
    BUCKET_NAME: !Ref DemoBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref DemoBucket, '/*']]

functions:
  upload:
    handler: handler.upload
    events:
      - httpApi:
          path: /upload
          method: post
          authorizer:
            name: apiAuth
    layers:
      - ${env:IMAGE_MAGICK_LAYER_ARN}

  authorizerFunc:
    handler: handler.auth

resources:
  Resources:
    DemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cb-demo-app-bucket